#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo ""
    echo "Usage: ./hw2runscript <benchmark> <automaton>"
    echo "  benchmark: blackscholes bodytrack canneal dedup fluidanimate freqmine streamcluster swaptions x264"
    echo "  automaton: A2 A3"
else
    bench=$1
    automaton=$2

    mkdir -p outputs/hw2/${automaton}/${bench}_8c_simsmall
    echo "./build/opt/zsim configs/hw2/${automaton}/${bench}_8c_simsmall.cfg > outputs/hw2/${automaton}/${bench}_8c_simsmall/${bench}.log 2>&1"
    ./build/opt/zsim configs/hw2/${automaton}/${bench}_8c_simsmall.cfg > outputs/hw2/${automaton}/${bench}_8c_simsmall/${bench}.log 2>&1 &
fi
